FROM centos:7

LABEL key="centos_httpd"

RUN yum install httpd -y
RUN yum install unzip -y
RUN rm -rf /var/www/html/index.html

ADD https://www.free-css.com/assets/files/free-css-templates/download/page290/cryptop.zip /var/www/html
WORKDIR /var/www/html

RUN unzip cryptop.zip

RUN mv cryptop-html/* .

EXPOSE 80

CMD httpd -DFOREGROUND